name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! We're here to help.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm wondering about...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: Which area does your question relate to?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Examples
        - Skills & MCP Protocol
        - Troubleshooting
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've already tried
      placeholder: I've tried...

  - type: textarea
    id: environment
    attributes:
      label: Environment Information (Optional)
      description: If relevant, provide information about your environment
      placeholder: |
        - Package version: 
        - Node.js version: 
        - MCP client: 
        - OS: 

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
